# cSpell: words gomod
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      "github-actions":
        patterns:
          - "*" # Group all GitHub Actions dependencies together
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      "docker":
        patterns:
          - "*" # Group all Docker dependencies together
