#
# Module manifest for 'Wsl-Manager' module
#
# Generated by: Antoine Martin
#
# Generated on: 05/05/2022
#


@{

    # Script module or binary module file associated with this manifest
    RootModule        = 'Wsl-Manager.psm1'

    # Version number of this module.
    ModuleVersion     = '2.0.0'

    # Supported PS Editions
    CompatiblePSEditions = 'Desktop', 'Core'

    # ID used to uniquely identify this module
    GUID              = 'bc998dd2-0e00-42cf-a564-4d9f99a1d044'

    # Author of this module
    Author            = 'Antoine Martin'

    # Company or vendor of this module
    CompanyName       = 'Openance'

    # Copyright statement for this module
    Copyright         = '(c) 2022 Antoine Martin. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'PowerShell cmdlet to quickly create minimal WSL distributions from various Linux distributions'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = '6.0'

    # Minimum version of the Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    DotNetFrameworkVersion = '5.1'

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    TypesToProcess    = @('Wsl-Manager.Types.ps1xml')

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess  = @('Wsl-Manager.Format.ps1xml')

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules     = @(
        'Wsl-SQLite\SQLite.ps1',
        'Wsl-Common\Wsl-Common.Types.ps1',
        'Wsl-Common\Wsl-Common.Helpers.ps1',
        'Wsl-Image\Wsl-Image.Types.ps1',
        'Wsl-Image\Wsl-Image.Helpers.ps1',
        'Wsl-Image\Wsl-Image.Cmdlets.ps1',
        'Wsl-Image\Wsl-Image.Docker.ps1',
        'Wsl-Image\Wsl-Image.Builtins.ps1',
        'Wsl-Image\Wsl-Image.Database.ps1',
        'Wsl-Image\Wsl-Image.Fetchers.ps1',
        "Wsl-Instance\Wsl-Instance.Helpers.ps1",
        "Wsl-Instance\Wsl-Instance.Types.ps1",
        "Wsl-Instance\Wsl-Instance.Cmdlets.ps1"
    )

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @("New-WslInstance", "Remove-WslInstance", "Export-WslInstance", "Get-WslInstance", "Invoke-WslInstance", "Invoke-WslConfigure", "New-WslImage", "Get-WslImage", "Sync-WslImage", "Remove-WslImage", "Get-WslImageSource", "Update-WslBuiltinImageCache", "New-WslImageSource", "Update-WslImageSource", "Save-WslImageSource", "Rename-WslInstance", "Stop-WslInstance", "Set-WslDefaultUid", "Set-WslDefaultInstance")

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    # cSpell: disable-next-line
    AliasesToExport   = @('Get-Wsl', 'gwsl', 'New-Wsl', 'nwsl', 'Remove-Wsl', 'rmwsl', 'Stop-Wsl', 'swsl', 'Invoke-Wsl', 'Rename-Wsl', 'mvwsl', 'cwsl', 'iwsl', 'Export-Wsl', 'ewsl', 'dwsl', 'gwsli', 'nwsli', 'rmwsli', "swsli", "gwsls", "uwsls", "swsls", "nwsls")

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    FileList          = @(
        "p10k.zsh",
        "configure.sh",
        "Wsl-Image\Wsl-Image.Types.ps1",
        "Wsl-Image\Wsl-Image.Helpers.ps1",
        "Wsl-Image\Wsl-Image.Cmdlets.ps1",
        "Wsl-Image\Wsl-Image.Docker.ps1",
        "Wsl-Image\Wsl-Image.Builtins.ps1",
        "Wsl-Image\Wsl-Image.Database.ps1",
        "Wsl-Image\Wsl-Image.Fetchers.ps1",
        "Wsl-Image\db.sqlite",
        "Wsl-Common\Wsl-Common.Types.ps1",
        "Wsl-Common\Wsl-Common.Helpers.ps1",
        "Wsl-SQLite\SQLite.ps1",
        "Wsl-SQLite\SQLiteHelper.cs",
        "Wsl-SQLite\bin\net48\WslSQLiteHelper.dll",
        "Wsl-SQLite\bin\net8.0\WslSQLiteHelper.dll",
        "Wsl-SQLite\bin\net8.0\WslSQLiteHelper.deps.json",
        "Wsl-SQLite\bin\net8.0-windows\WslSQLiteHelper.dll",
        "Wsl-SQLite\bin\net8.0-windows\WslSQLiteHelper.deps.json",
        "Wsl-Instance\Wsl-Instance.Helpers.ps1",
        "Wsl-Instance\Wsl-Instance.Types.ps1",
        "Wsl-Instance\Wsl-Instance.Cmdlets.ps1"
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This can also include a PSData hash table with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags have been applied to this module. They facilitate the discovery of modules in online galleries.
            Tags       = @("WSL", "Windows", "Subsystem", "Linux", "Arch", "Alpine", "Ubuntu")

            # URL for the license of this module.
            LicenseUri = 'https://github.com/antoinemartin/PowerShell-Wsl-Manager/blob/main/LICENSE'

            # URL for the main website of this project.
            ProjectUri = 'https://github.com/antoinemartin/PowerShell-Wsl-Manager'

            # URL for an icon representing this module.
            # IconUri = ''

            # ReleaseNotes property of this module
            # ReleaseNotes = ''

        } # End of PSData hash table

    } # End of PrivateData hash table

    # HelpInfo URI of this module
    HelpInfoURI       = 'https://github.com/antoinemartin/PowerShell-Wsl-Manager/blob/main/README.md'

    # Default command prefix exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
