@repository = antoinemartin/powershell-wsl-manager/alpine-base

###
# Retrieve github packages token
# @name get_token
https://ghcr.io/token?service=ghcr.io&scope=repository:{{repository}}:pull

###
# Get image index
# @name image_index
GET https://ghcr.io/v2/{{repository}}/manifests/latest
Authorization: Bearer {{get_token.response.body.token}}
Accept: application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.list.v2+json


###
# Get image manifest
# @name image_manifest
GET https://ghcr.io/v2/{{repository}}/manifests/{{image_index.response.body.manifests[0].digest}}
Authorization: Bearer {{get_token.response.body.token}}
Accept: application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v2+json

###
# Get image config
# @name image_config
GET https://ghcr.io/v2/{{repository}}/blobs/{{image_manifest.response.body.config.digest}}
Authorization: Bearer {{get_token.response.body.token}}
Accept: application/vnd.oci.image.config.v1+json, application/vnd.docker.distribution.manifest.v2+json

###
# Get list of available WSL distributions
GET https://raw.githubusercontent.com/antoinemartin/PowerShell-Wsl-Manager/main/docs/assets/distributions.json HTTP/1.1

###
# Get incus root fs
GET https://images.linuxcontainers.org/streams/v1/index.json HTTP/1.1


###
# Get incus image
GET https://images.linuxcontainers.org/images/alpine/3.22/amd64/default HTTP/1.1
Accept: text/text/html

###
GET https://images.linuxcontainers.org/images/alpine/3.22/amd64/default/20250816_13%3A00/ HTTP/1.1

###
GET https://images.linuxcontainers.org/images/alpine/3.22/amd64/default/20250816_13%3A00/SHA256SUMS HTTP/1.1
