# Navigation
nav:
  - About:
      - index.md
      - Quick Start: quick-start.md
      - Acknowledgements: Acknowledgements.md
  - Usage:
      - usage/index.md
      - Create Instances: usage/create-instances.md
      - Manage Instances: usage/manage-instances.md
      - Manage Images: usage/manage-images.md
      - Command Reference: usage/reference
  - Examples:
      - examples/index.md
      - Create Image from Docker Image: examples/create_distribution_from_docker_image.md
      - Docker with Arch: examples/docker_with_arch.md
      - Centralized Signature and Key Management: examples/central_signature_and_key_management.md
  - Development:
      - Getting Started: development/getting-started.md
      - Add a New Builtin Distro: development/add-a-new-builtin-distro.md
      - Build OCI Images: development/build-oci-images.md
      - Testing: development/testing.md
