# Copyright 2022 Antoine Martin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Test Module
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x

      - name: Build SQLite Helper
        shell: pwsh
        run: |
          ./Wsl-SQLite/Build-SQLiteHelper.ps1 -Configuration Release -Clean

      - name: Test the module
        shell: pwsh
        run: |
          ./hack/Invoke-Tests.ps1 -All -Format 'JaCoCo'

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: (!cancelled())
        with:
          name: test-results
          path: |
            testResults.xml
            coverage.xml

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: testResults.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: powershell

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: testResults.xml
          flags: powershell

  build-nuget-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x

      - name: Build SQLite Helper
        shell: pwsh
        run: |
          ./Wsl-SQLite/Build-SQLiteHelper.ps1 -Configuration Release -Clean
      - name: Build the module
        shell: pwsh
        run: |
          ./hack/Build-NugetPackage.ps1 -Version ${{ github.ref_name }}

      - name: Upload package
        uses: actions/upload-artifact@v4
        if: (!cancelled())
        with:
          name: nuget-package
          path: |
            repo/*.nupkg

      - name: Test package installation
        shell: pwsh
        run: |
          $nupkgPath = Get-ChildItem -Path ./repo/*.nupkg | Select-Object -First 1
          Expand-Archive $nupkgPath ~/.local/share/powershell/Modules/Wsl-Manager/2.0.0
          Import-Module Wsl-Manager
          Get-WslBuiltinImage
          Get-WslImage -Source All
          Sync-WslImage alpine-base
